---
title: "Data viz"
author: "Sarah Bisgaard Olesen"
date: "17/6/2021"
output: html_document
---

```{r setup}
#Load packages
source(here::here("R/package_loading.R"))

#load the tidied dataset 
load(here::here("data/nhanes_small.rda"))

```

# One variable plots

```{r continuous-variables}

## Normalvis laves der kun et plot per chunk, men dette kan fungere lidt som en "kogebog"

# Create density plot for BMI
ggplot(nhanes_small, aes(x = bmi)) +         #aes er, hvad der skal plottes
    geom_density()                           #typen af plot


# Create histogram for BMI
ggplot(nhanes_small, aes(x = bmi)) +
    geom_histogram()


```


```{r discrete-variables}

# Create count barplot for sex
ggplot(nhanes_small, aes(x = sex)) +
    geom_bar()

# Create count barplot for diabetes
ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()

```

```{r remove-missing-diabetes}

# Create count barplot for diabetes without NA
nhanes_tidied <- nhanes_small %>% 
    filter(!is.na(diabetes))

# Save as
usethis::use_data(nhanes_tidied, overwrite = TRUE)


# Create count barplot for diabetes without NA
ggplot(nhanes_tidied, aes(x = diabetes)) +
    geom_bar()

```

# Plotting two variables

```{r 2-continuous-variables}
bmi_chol <- ggplot(nhanes_tidied, aes(x = bmi, y = tot_chol))

bmi_chol +
    geom_point()

bmi_chol +
    geom_hex()

bmi_chol +
    geom_smooth()

bmi_chol +
    geom_hex() +
    geom_smooth()
    
```

```{r 2-discrete-variables}

two_discrete <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex))

two_discrete +
    geom_bar()

# "dodged" (side-by-side) bar plot
two_discrete +
    geom_bar(position = position_dodge())

```

```{r discrete-continuous-variables}

two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

two_mixed +
    geom_boxplot()

two_mixed +
    geom_jitter()

two_mixed +
    geom_violin()

```

# Exercise to make plots with one or two variables

```{r exercise-11-5}
# 1a. Distribution of age
ggplot(nhanes_tidied, aes(x = age)) +
    geom_histogram()

# 1b. Distribution of age of diabetes diagnosis
ggplot(nhanes_tidied, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now
ggplot(nhanes_tidied, aes(x = smoke_now)) +
    geom_bar()

nhanes_small %>% 
    drop_na(smoke_now) %>% 
    ggplot(aes(x = smoke_now)) +
    geom_bar()

# 2b. Number of people who are physically active
ggplot(nhanes_tidied, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()
    
# 4. Physically active people with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, y = poverty)) +
    geom_violin()
```

#Visualizing three or more variables

```{r using-color}

# Plot systolic blood pressure in relation to sex and diabetes status
nhanes_tidied %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, color = diabetes)) +
    geom_boxplot()

# Plot BMI in relation to systolic blood pressure and age
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, color = age)) +
    geom_point()


#nhanes_small %>% 
    #drop_na(sex | bp_sys_ave | diabetes) %>% 
    #ggplot(aes(x = sex, y = bp_sys_ave, color = diabetes)) +
    #geom_point()

# Plot BMI in relation to systolic blood pressure and diabetes status
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = diabetes)) +
    geom_point()


```

```{r using-faceting}

# Plot BMI in relation to systolic blood pressure and diabetes status using
# faceting by column (side by side)
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) +
    geom_point() +
    facet_grid(cols = vars(diabetes))

# faceting by row (stacked)
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) +
    geom_point() +
    facet_grid(rows = vars(diabetes))

# Plot BMI in relation to systolic blood pressure, age, sex and diabetes status (5 variables)
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, color = age)) +
    geom_point() +
    facet_grid(rows = vars(diabetes), cols = vars(sex))

```

